@startuml
!pragma layout smetana

class Main{
+ static void main(String[] args)
}
class loginMenu{
- void registerUser()
+ login()
}
class MainMenu{
+ displayMovie
+ displayShow
+ displayCategories
+ displayMyList
+ displayWatched

 + void endSession()
}

class User{
- LinkedList<List> userList
+ User(String name)
+ User(String name, passWord)
+ String getPassWord
+ String setPassWord
+ String getName()
+ String setName()
+ String toString()
}
class FileIO{
+ ArrayList<String> readUserData(String path)
+ void saveData(ArrayList<String> items, String path)
+ ArrayList<String> readMovieData(String path)
+ ArrayList<String> readShowData(String path)
}

class TextUI{
- Scanner scanner
+ void displayMsg(String s)
+ int promptNumeric(String msg)
+ String promptText(String msg)
+ int promptChoice(String msg, ArrayList<String> list)
}

class List{
- String [] movieData
- String [] showData
- categories [] Lists
+ searchCategories
+ userList
}
class Action{
+ save
+ delete
+ watch
}


Main *-- loginMenu
loginMenu *-- MainMenu
MainMenu *-- TextUI
MainMenu *-- List
MainMenu *-- User
MainMenu *-- FileIO
User *-- Action

@enduml