@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana


object User
object LoginMenu
object MainMenu
object Film
object Serie
object Kategori
object List
object Fejl
object UserName
object PassWord
object LoginInformation
object Action
object Se
object Gem
object Slet

MainMenu <-- User
MainMenu <-- Film
MainMenu <-- Serie
MainMenu <-- Action
LoginInformation *-- User: has-a
User *-- List: has-a
User *-- UserName: has-a
User *-- PassWord: has-a
Action *-- User: has-a
'Kategori *-- HovedMenu: has-a
LoginMenu *-- MainMenu
LoginInformation *-- LoginMenu: has

List <|-- Kategori : is - a
List <|-- Film: is - a
List <|-- Serie: is - a
Kategori *-- Film: has-a
Kategori *-- Serie: has-a

'Action'
List <|-- Action
Action <|-- Se : is - a
Action <|-- Gem : is - a
Action <|-- Slet : is - a

@enduml